### ISSUE TITLE
 position of the syntax highlighting in the floating window is always offset 

### ISSUE THREAD

**Issue by gao634209276** [antoinemadec/coc-fzf#58] opened 2020-08-19 09:43 UTC
![image](https://user-images.githubusercontent.com/17423623/90618753-fb4bf700-e242-11ea-95da-8c80761e64d5.png)

The character position of the syntax highlighting in the floating window is always offset by 1 character.
The error is shown in the above picture, who can fix it, thanks

@sethfowler @expipiplus1 @asermax @felippemr @Frederick888

**Comment by antoinemadec** [comment] 2020-08-19 16:36
@gao634209276 I cannot reproduce your issue. My preview just work fine:
![preview_correct](https://user-images.githubusercontent.com/10830594/90664038-4f34ec80-e1ff-11ea-942f-3542f7d97934.png)

Could you please provide:
1. Vim/Neovim version
2. bat version
3. **minimal** vimrc
4. the exact steps to reproduce the issue

**Comment by antoinemadec** [comment] 2020-08-19 18:56
@gao634209276 , you opened an issue with fzf.vim here: https://github.com/junegunn/fzf.vim/issues/1096
Why did you also open an issue on coc-fzf?
Why did you not reference the fzf.vim issue on this issue?

Closing this issue as this is a fzf.vim issue, not a coc-fzf issue.
If I may, if you want your issue to be resolved on fzf.vim, please consider providing a minimal testcase.
A screenshot is generally not enough to understand/narrow down an issue.

**Closed by antoinemadec** 2020-08-19 18:56 UTC
