### ISSUE TITLE
Do not block if LSP server has not finished starting up

### ISSUE THREAD

**Issue by stellarhoof** [antoinemadec/coc-fzf#92] opened 2021-02-24 15:34 UTC
**Is your feature request related to a problem? Please describe.**

Open a file where LSP takes a while to startup and immediately invoke `CocFzfList`. It blocks the UI until the server is done.

**Describe the solution you'd like**

Not block the UI. Perhaps even display an error message saying that the server is starting up.

**Comment by antoinemadec** [comment] 2021-02-24 19:25
Please fill the bug template with precise instructions and minimal vimrc to reproduce.

**Comment by antoinemadec** [comment] 2021-03-21 19:16
@stellarhoof closing since I don't knoow how to reproduce it,
Feel free to open a new issue if you have a minimal vimrc and steps to reproduce this.

**Closed by antoinemadec** 2021-03-21 19:16 UTC
