### ISSUE TITLE
Not in terminal mode after selecting an item in CocFzfList

### ISSUE THREAD

**Issue by Frederick888** [antoinemadec/coc-fzf#55] opened 2020-08-15 17:15 UTC
**Steps to reproduce**:

1. `:CocFzfList`
2. Select an item and hit enter

**Actual result**:

Selected list is shown but in normal mode.

**Expected result**:

Terminal mode is used by default.

**Comment by antoinemadec** [comment] 2020-08-15 19:53
Which version of Vim/Neovim are you using?

This happens on old versions, but should not happen on more recent versions.
I used to have the logic to add `i` when necessary, but I removed it as soon as this had been fixed on Vim/Neovim:
https://github.com/antoinemadec/coc-fzf/commit/66a2892265a558f5bcb0f3ed924d26cdacdb7db0

That being said, that logic would not even have fixed your issue since you are "coming from" `CocFzfList` which means all lists would be affected.

Please let me know if upgrading your Vim/Neovim and plugins fixes it.

**Comment by Frederick888** [comment] 2020-08-16 08:39
I'm using NeoVim v0.4.4 and everything's up-to-date. On the other hand I tested again on Vim 8.2 and it did enter terminal mode automatically. Perhaps it's something we need to cater for NeoVim only?

**Comment by antoinemadec** [comment] 2020-08-16 14:40
Can you build neovim from source and try again?

**Comment by antoinemadec** [comment] 2020-08-16 14:41
Or use snap nightly build.

**Comment by Frederick888** [comment] 2020-08-17 00:25
It seems to have been resolved in the latest NeoVim v0.5.0 build.

I just tested on NeoVim v0.4.4 under macOS and it was the same problem. Then I tried out the v0.5.0 build (published 11 hours ago) and the problem was gone.

Can we bring the workaround back for NeoVim before the fix (out of curiosity, which?) lands in their stable channel?

**Comment by antoinemadec** [comment] 2020-08-17 01:02
PR welcome, but I'd rather not spend time and energy on this.
If you want to do this you have to add a 'first_call' arg to each function and add a feedkeys(i) if not first_call (see my previous commit).
That's not hard, but it would add a lot of code for a small bug that is non existent on up-to-date vim/neovim.

**Comment by antoinemadec** [comment] 2020-08-17 01:07
Let me know what you think :relaxed:

**Comment by antoinemadec** [comment] 2020-08-17 01:10
Actually, the code i wrote in my previous commit should be enough. We would just need to add a check on the Vim/Neovim version.
Once again I won't do it, but i will accept a PR if you can pin point which patch fixed this.

**Comment by Frederick888** [comment] 2020-08-17 09:37
Well, on one hand I agree that creating temporary workarounds is not something every open-source project should do, on the other hand based on NeoVim's pace of release we probably have to wait until late this year for v0.4.5 (and it may or may not fix this). But the `lists` list is something that I seldom use so I guess can just live with it.

Shall we keep this ticket open just to track this issue? And let's see if it annoys someone else enough to submit a PR lol

**Comment by antoinemadec** [comment] 2020-08-17 16:42
> Shall we keep this ticket open just to track this issue? And let's see if it annoys someone else enough to submit a PR lol

Agreed.
If people ask for it, I will reintroduce my previous commit with a global variable, like `g:coc_fzf_force_terminal_mode` or something like that. That way we don't have to pin point it to the precise patch that fixes it.

Let's close this issue once the final Nvim 0.5 is release (the 0.5 available right now is a dev version).

**Comment by antoinemadec** [comment] 2020-08-18 19:09
@Frederick888  @Avi-D-coder , here is the commit fixing this in Neovim: https://github.com/neovim/neovim/commit/721f69c4af8bc81ba04088e7b56f8cdba653b418

This correspond to:
```
> nvim --version
NVIM v0.5.0-571-g721f69c4a
```
which is commit **571** of nvim **v0.5.0**.

The issue is that I did not find any mechanism inside neovim to get the version and commit number, to test whether the commit is present or not.
So I opened a feature request here: https://github.com/neovim/neovim/issues/12773

Once we have a way to check if a commit is present neovim, I will re-introduce the bug fix when necessary.

**Comment by antoinemadec** [comment] 2020-08-18 20:48
@Frederick888 @Avi-D-coder could you please upgrade **coc-fzf** and confirm it fixed your issue?

Thanks!

**Closed** 2020-08-18 20:47 UTC

**Comment by Frederick888** [comment] 2020-08-18 23:10
Yup, can confirm it's fixed! Thanks!

**Comment by Avi-D-coder** [comment] 2020-08-31 19:45
This is still broken for me, both references and go to def.
```
vim version: NVIM v0.5.0-646-g2bbbb34ce
node version: v14.9.0
coc.nvim version: 0.0.78
```

**Comment by antoinemadec** [comment] 2020-08-31 20:33
There is no "entering the terminal" for references and go to def.
I doubt your issue is related to this issue.

Please look at the branches of coc and coc-fzf you are using, see Readme's installation.
If that's not it, please open a new issue and follow the template.

**Comment by antoinemadec** [comment] 2020-09-01 15:15
@Avi-D-coder , after looking at your nvim version, it seems recent enough.
I cannot reproduce this issue on recent nvim versions.

Please create a new issue to describe precisely the problem.
I cannot help without sufficient info.
